---
title: "R Notebook"
---
# our goal of collecting a dataset about liver disease is to facilitate research and analysis about it. since liver disease is more common and can be fatal we are aiming to classify the patients and analyze the data and correlations between the data.

# link to the source of our dataset: https://www.kaggle.com/uciml/indian-liver-patient-records

# general info about the dataset:
# it has 11 columns which are:
# age (numeric)
# gender (symmetric binary)
# Total_Bilirubin (numeric)
# direct_Bilirubin (numeric)
# Alkaline_Phosphotase (numeric)
# Alamine_Aminotransferase (numeric)
# Aspartate_Aminotransferase (numeric)
# Total_Protiens (numeric)
# Albumin (numeric)
# Albumin_and_Globulin_Ratio (numeric)
# Dataset (asymmetric binary)

# and has 583 objects

# and class label (dataset) which indicates (1 disease or 2 no disease)

# The getwd() function tells you what the current working directory is
getwd()

# setwd function to change the directory you work on 
setwd("C:/Users/arwa_/OneDrive/المستندات/GitHub/datamining-project")

# Importing the dataset
# read file named "indian_liver_patient" and save it in dataframe named "dataset"
dataset = read.csv("C:/Users/arwa_/OneDrive/المستندات/GitHub/datamining-project/dataset/indian_liver_patient.csv")

# data analysis

# raw data and summary of the dataset
View(dataset)
str(dataset)
summary(dataset)

# Dealing with the missing values - Outliers 

# Checking NULL, FALSE means no null, TRUE cells means the value of the cell is null
is.na(dataset)

# to find the total null values in the dataset
sum(is.na(dataset))

# find which column has missing values
listMissingColumns <- colnames(dataset)[ apply(dataset, 2, anyNA)]
print(listMissingColumns)

# stastical summaries
summary(dataset$age)
summary(dataset$Total_Bilirubin)
summary(dataset$direct_Bilirubin)
summary(dataset$Alkaline_Phosphotase)
summary(dataset$Alamine_Aminotransferase)
summary(dataset$Aspartate_Aminotransferase)
summary(dataset$Total_Protiens)
summary(dataset$Albumin)
summary(dataset$Albumin_and_Globulin_Ratio)

# data visualization

# Create a bar plot
ggplot(indian_liver_patient, aes(x = Age, y = Total_Bilirubin)) +geom_bar(stat = "identity", fill = "steelblue") + labs(x = "Age", y = "Total Bilirubin", title = "Age vs. Total Bilirubin Bar Plot")
# Create a scatterplot
plot(indian_liver_patient$Alamine_Aminotransferase, 
     indian_liver_patient$Aspartate_Aminotransferase, 
     xlab = "Alamine Aminotransferase", 
     ylab = "Aspartate Aminotransferase",
     main = "Scatterplot of Alamine Aminotransferase vs. Aspartate Aminotransferase",
     pch = 16, col = "blue")

# convert a gender value to numeric 
indian_liver_patient$Gender[indian_liver_patient$Gender == "Male"] <- 0
indian_liver_patient$Gender[indian_liver_patient$Gender == "Female"] <- 1

 # There is linear relationship between Aspartate_Aminotransferase and Alamine_Aminotransferase. We can remove one of the features.  
 
# data preprocessing

# NOTE: after visualization and before replacing delete redundant features if Dr approves

# Replace missing Data with mean or median (median if outliers found) since there is only four tuples with a missing value
dataset$Albumin_and_Globulin_Ratio = ifelse(is.na(dataset$Albumin_and_Globulin_Ratio), ave(dataset$Albumin_and_Globulin_Ratio, FUN =function(x) mean(x,na.rm=TRUE)), dataset$Albumin_and_Globulin_Ratio)
sum(is.na(dataset))



